// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
    saveTempFile: (data: File | ArrayBuffer) => Promise<string>;
}

declare interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    stepConverter: {
        convertStep: (filePath: string) => Promise<{
            success: boolean;
            stl_data?: string;
            pipe_measurements?: {
                inner_diameter: number;
                outer_diameter: number;
                wall_thickness: number;
            };
            error?: string;
        }>;
    };
    cleanup: {
        clearStorage: () => Promise<void>;
    };
}
